// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	golibshared "github.com/mrapry/go-lib/golibshared"
	mock "github.com/stretchr/testify/mock"
)

// ServiceCaterpillar is an autogenerated mock type for the ServiceCaterpillar type
type ServiceCaterpillar struct {
	mock.Mock
}

// GetDataUnit provides a mock function with given fields: ctx, code
func (_m *ServiceCaterpillar) GetDataUnit(ctx context.Context, code string) <-chan golibshared.Result {
	ret := _m.Called(ctx, code)

	var r0 <-chan golibshared.Result
	if rf, ok := ret.Get(0).(func(context.Context, string) <-chan golibshared.Result); ok {
		r0 = rf(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan golibshared.Result)
		}
	}

	return r0
}
